### ISSUE TITLE
Caching odds acts weird

### ISSUE THREAD

**Issue by greenlucid** [seer-pm/demo#100]
These odds are definitely not right

<img width="550" alt="image" src="https://github.com/user-attachments/assets/08f3962b-572b-4346-a68b-600f90a47aa6">

And, sometimes I experienced that the odds were flipped (it was rendering kamala odds for trump and viceversa). This has to be related to the indexing patch I made

Happens for both OutcomeInfo and Outcomes

**Comment by nvm1410** [comment]
I think the odds change very fast for this market. I updated the stale time to 0 so it will refetch on reload now.

**Comment by greenlucid** [comment]
This is definitely broken, no one is trading

**Comment by greenlucid** [comment]
Like, if you simulate a trade of 1 sDAI you'll see the actual price on the right, which differs from the odds. I'm investigating whats up, it seems like the odds are out of order? Thats what I see when I log. Something thats persisting seems to be altering the order

Maybe it's a bug in persist-react-query + the other persisting state solution you were using + the sort I used to reorder the indexes?

<img width="1112" alt="image" src="https://github.com/user-attachments/assets/4096d7c2-2c3a-4986-8e20-851d8102a986">

**Comment by nvm1410** [comment]
I think setting BUY_AMOUNT too low when getting the price may have cause the fluctuation. I tested it with 1000 and the result is consistent every reload

**Comment by greenlucid** [comment]
I didn't believe you at first but it seems that's the case, what the hell. This looks like a swapr bug then because it works fine in Mainnet

**Comment by greenlucid** [comment]
did git checkout to a previous version and replicated the issue, so it's not related to caching
