### ISSUE TITLE
Do not force integer

### ISSUE THREAD

**Issue by Seer-Sir** [seer-pm/demo#201]
Rounding is only a default if no method was specified. It's possible to non integers (up to 18 decimal)
![image](https://github.com/user-attachments/assets/4d00d768-a5c8-4cb8-9bcd-e22856056b6a)

- Modify the warning saying "If no rounding method is specified"
- Allow to enter non round valus (look at the way realitio is doing it).

**Comment by nvm1410** [comment]
The logic already handle converting and submitting non integers up to 18 decimals, I just enabled the input to do so and remove the warning.
