### ISSUE TITLE
Link to reality question even if not opened yet

### ISSUE THREAD

**Issue by Seer-Sir** [seer-pm/demo#52]
Currently, there is no easy way to identify the reality question before a market is open. Link to it:
![image](https://github.com/user-attachments/assets/75d467f3-dec9-4064-b08e-ce4c49a8bf07)

**Comment by xyzseer** [comment]
on multi scalar markets it opens a modal with all the questions
![image](https://github.com/user-attachments/assets/54a2e0df-6fd4-4dae-b365-37e3a4eadd36)
