### ISSUE TITLE
"Create Market" could be replaced with "Create"

### ISSUE THREAD

**Issue by greenlucid** [seer-pm/demo#60]
<img width="532" alt="image" src="https://github.com/user-attachments/assets/1fa3a09b-b4e5-44d5-a871-7e9d93c31dbf">

fully open window in m1 small laptop has Create Market overlap a bit. Renaming to "Create" might get the job done and also have evident meaning? (after you click you see how it allows creating a market)

**Comment by nvm1410** [comment]
Updated. https://github.com/seer-pm/demo/commit/01db328610144a2208590a7d725fa2fd8832b4e9
