### ISSUE TITLE
The sorting by open interest is broken

### ISSUE THREAD

**Issue by Seer-Sir** [seer-pm/demo#78]
"[Will Donald Trump be sentenced to any time behind bars in 2024?](https://seer.pm/#/markets/100/0xbc82402814f7Db8736980c0DEbb01Df6AAd8846E/)" shows as 2.79k of open interest but is displayed below other market with lower opened interest.
![image](https://github.com/user-attachments/assets/f82fe1f6-133c-4819-a75e-c89510b52acc)

**Comment by greenlucid** [comment]
What filtering settings did you use to replicate this broken sorting? I see it working fine
What did you expect?

**Comment by xyzseer** [comment]
I see it working well now, I fixed the open interest on a766b699e7963ded3982137cbc33b11301c3a8e5 . Let me know if the error still happens.
