### ISSUE TITLE
The add liquidity button of this market adds the wrong liquidity

### ISSUE THREAD

**Issue by Seer-Sir** [seer-pm/demo#90]
![image](https://github.com/user-attachments/assets/eb528028-0b4d-4e41-8b5b-927aeb80e518)
![image](https://github.com/user-attachments/assets/0cc0b2ee-c394-49a0-8af5-f1a58de8e788)

"R House R Senate" add liquidity button opens the liquidity for "R House D Senate".

**Comment by greenlucid** [comment]
Fixed here hopefully
https://github.com/seer-pm/demo/pull/89
